'use client';

import { createContext, useContext, ReactNode, useEffect, useState } from 'react';

export type Language = 'zh' | 'en' | 'ja';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const translations: Record<string, string> = {
  // Navigation
  'nav.home': 'Home',
  'nav.dashboard': 'Dashboard',
  'nav.chat': 'Chat with Agent',
  'nav.chatMobile': 'Agent',
  'nav.compare': 'Compare',
  'nav.database': 'Database',
  'nav.reports': 'Reports',
  'nav.settings': 'Settings',

  // Common
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.success': 'Success',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.close': 'Close',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.sort': 'Sort',
  'common.reset': 'Reset',
  'common.apply': 'Apply',
  'common.calculate': 'Calculate',
  'common.refresh': 'Refresh',
  'common.clearFilters': 'Clear filters',
  'common.pending': 'Pending',
  'common.dismiss': 'Dismiss',
  'common.reviews': 'Reviews',
  'common.games': 'Games',
  'common.languages': 'Languages',
  'common.filters': 'Filters',
  'common.all': 'All',
  'common.recommended': 'Recommended',
  'common.notRecommended': 'Not recommended',
  'common.issues': 'Issues',
  'common.requests': 'Requests',
  'common.evidence': 'Evidence',
  'common.labels': 'Labels',
  'common.noData': 'No data',

  // Filters
  'filters.allSentiment': 'All',
  'filters.allTime': 'All time',
  'filters.last30Days': 'Last 30 days',
  'filters.last90Days': 'Last 90 days',
  'filters.last12Months': 'Last 12 months',
  'filters.customRange': 'Custom range',
  'filters.allHelpful': 'All helpful',
  'filters.helpfulVotes10': '10+ votes',
  'filters.helpfulVotes25': '25+ votes',
  'filters.helpfulVotes50': '50+ votes',
  'filters.allPlaytime': 'All playtime',
  'filters.playtimeLt2h': '<2h playtime',
  'filters.playtime2to20h': '2–20h playtime',
  'filters.playtime20hplus': '20h+ playtime',
  'filters.helpfulVotes': '{count}+ helpful',
  'filters.languageChip': 'Lang: {lang}',

  // Game Context
  'gameContext.currentGame': 'Current game',
  'gameContext.noGame': 'No game',
  'gameContext.noSavedGames': 'No saved games',
  'gameContext.analyzeNew': 'Analyze new game',
  'gameContext.filteredReviews': 'Filtered reviews: {filtered} / {total}',
  'gameContext.sampledReviews': 'Sampled reviews: {total}',
  'gameContext.filtersApply': 'Filters apply to your current game reviews.',
  'gameContext.selectGameHint': 'Select a game to see review totals.',
  'gameContext.analyzeToSeeReviews': 'Analyze this game to see review totals.',
  'gameContext.activeFilters': 'Active filters:',
  'gameContext.noFiltersActive': 'No filters active',

  // Dashboard
  'dashboard.title': 'Dashboard',
  'dashboard.analyze': 'Analyze',
  'dashboard.update': 'Refresh latest 1,000 reviews',
  'dashboard.analyzing': 'Analyzing...',
  'dashboard.noGames': 'No games analyzed yet',
  'dashboard.recommendation': 'Recommendation',
  'dashboard.issueRate': 'Issue rate',
  'dashboard.requestRate': 'Request rate',
  'dashboard.welcome': 'Welcome',
  'dashboard.welcomeTo': 'Welcome to STRA',
  'dashboard.subtitle': 'Understand what players really think. Start with a new Steam analysis or jump back into a recent report.',
  'dashboard.newAnalysis': 'New game analysis',
  'dashboard.newAnalysisDesc': 'Search Steam to begin a fresh review classification run.',
  'dashboard.searchPlaceholder': 'Search for a game (e.g., Baldur\'s Gate 3)',
  'dashboard.searching': 'Searching...',
  'dashboard.noGamesFound': 'No games found. Try a different search term.',
  'dashboard.recentAnalyses': 'Recent analyses',
  'dashboard.recentDesc': 'Open a saved dashboard from your latest runs.',
  'dashboard.viewAll': 'View all',
  'dashboard.noAnalyses': 'No analyses yet',
  'dashboard.noAnalysesDesc': 'Search for a game to start your first analysis.',
  'dashboard.openReviews': 'Open reviews',
  'dashboard.filtersActive': 'Active',
  'dashboard.showFilters': 'Show all filters',
  'dashboard.hideFilters': 'Hide all filters',
  'dashboard.lastMonthOnly': 'Last 30 days',
  'dashboard.categoriesOverview': 'Categories overview',
  'dashboard.topIssues': 'Top issues',
  'dashboard.topRequests': 'Top feature requests',
  'dashboard.newSearch': 'New Search',
  'dashboard.settings': 'Settings',
  'dashboard.costPreview': 'Cost Preview',
  'dashboard.calculating': 'Calculating...',
  'dashboard.costPreviewHint': 'Click Calculate to preview cache reuse and ETA.',
  'dashboard.processing': 'Processing',
  'dashboard.newReviews': 'New reviews',
  'dashboard.cached': 'Cached',
  'dashboard.cacheReuse': 'Cache reuse',
  'dashboard.etaRough': 'ETA (rough)',
  'dashboard.llmCalls': 'LLM calls',
  'dashboard.costLabel': 'Cost',
  'dashboard.queueRunning': 'Analysis running • {count} in queue',
  'dashboard.queueStatus': 'Queue: {count} running',

  // Chat
  'chat.title': 'Chat with Agent',
  'chat.subtitle': 'Your intelligent conversation partner',
  'chat.placeholder': 'Type your message...',
  'chat.send': 'Send',
  'chat.newChat': 'New Chat',
  'chat.history': 'Chat History',
  'chat.context': 'Context',
  'chat.noConversations': 'No conversations yet',
  'chat.selectGames': 'Select up to 2 games to search reviews:',
  'chat.clearSelection': 'Clear selection',
  'chat.noStarredGames': 'No starred games yet',
  'chat.loadingGames': 'Loading games...',
  'chat.chatWithData': 'Chat with Your Data',
  'chat.startConversation': 'Start a conversation',
  'chat.askAnything': 'Ask me anything!',
  'chat.sources': 'Sources',
  'chat.sourcesUsed': 'Sources used',
  'chat.showSources': 'Show sources',
  'chat.hideSources': 'Hide sources',
  'chat.promptPresets': 'Prompt presets',
  'chat.selectGameNotice': 'Select a game to run this prompt.',
  'chat.copySuccess': 'Answer copied',
  'chat.copyFailed': 'Copy failed',
  'chat.copy': 'Copy',
  'chat.regenerate': 'Regenerate',
  'chat.suggestedQuestions': 'Suggested questions',
  'chat.pleaseClarify': 'Please clarify',
  'chat.selectGame': 'Select a game',
  'chat.searchFor': 'Search for {game}',
  'chat.searchForGames': 'Search for games',
  'chat.loadingConversation': 'Loading conversation...',
  'chat.export': 'Export',
  'chat.newMobile': 'New',
  'chat.gamesSelected': '{count} games selected',
  'chat.gameSelected': '{count} game selected',
  'chat.selectGamesTitle': 'Select games to chat about',
  'chat.chooseGames': 'Choose up to 2 games to unlock chat',
  'chat.askAfterSelection': '{count} selected. Ask a question below.',
  'chat.noAnalyzedGames': 'No analyzed games found',
  'chat.analyzeFirst': 'Analyze a game before chatting.',
  'chat.goDashboard': 'Go to dashboard',
  'chat.selected': 'Selected',
  'chat.pickQuestion': 'Suggested questions',
  'chat.pickQuestionHint': 'Pick one to start, or type your own question below.',
  'chat.chattingWith': 'Chatting with:',
  'chat.noDate': 'No date',
  'chat.downloadPng': 'Download PNG',
  'chat.helpful': 'Helpful response',
  'chat.notHelpful': 'Not helpful',
  'chat.searchingReviews': 'Searching reviews...',
  'chat.thinking': 'Thinking...',
  'chat.inputHint': 'Press Enter to search reviews and get insights',
  'chat.selectGameToStart': 'Select at least one game to start chatting',
  'chat.errorProvider': '智能问答暂时无法连接 AI 服务，请在“系统设置”中检查 AI 服务提供商和 API Key 后重试。',
  'chat.errorRateLimit': '请求过于频繁，请稍后再试。',
  'chat.errorGeneric': '智能问答暂时无法处理这个问题，请稍后重试。',

  // Compare
  'compare.title': 'Game Comparison',
  'compare.selectGames': 'Select at least 2 games',
  'compare.categoryOverview': 'Category Overview',
  'compare.categoryRecommendation': 'Category recommendation',
  'compare.sortBy': 'Sort by:',
  'compare.biggestDiff': 'Biggest Difference',
  'compare.highestRating': 'Highest Rating',
  'compare.lowestRating': 'Lowest Rating',
  'compare.mostReviews': 'Most Reviews',
  'compare.onlySignificant': 'Only show significant differences (>10%)',
  'compare.resetFilters': 'Reset filters',
  'compare.sampleReviews': 'Sample Reviews',
  'compare.exampleReviews': 'Example reviews from each game for this subcategory',
  'compare.noGames': 'No games to compare',
  'compare.analyzeFirst': 'Analyze some games first to compare them here.',
  'compare.selectGamesDesc': 'Select Games',
  'compare.selected': 'Selected',
  'compare.visualComparison': 'Visual comparison across all categories',
  'compare.swapPrompt': 'Only 2 games can be compared. Swap in {game}?',
  'compare.swapHint': 'Choose a game to replace.',
  'compare.swapReplace': 'Replace {game}',

  // Database
  'database.title': 'Database Explorer',
  'database.subtitle': 'Browse every stored review.',
  'database.stats': 'Database statistics',
  'database.loadingStats': 'Loading stats...',
  'database.games': 'Games',
  'database.reviews': 'Reviews',
  'database.starred': 'Starred',
  'database.labels': 'Labels',
  'database.noData': 'No local data yet',
  'database.noDataDesc': 'Run your first analysis to populate the database.',
  'database.filters': 'Dataset filters',
  'database.filtersDesc': 'Search and filter across the entire database.',
  'database.searchText': 'Search text',
  'database.searchPlaceholder': 'Search review text',
  'database.game': 'Game',
  'database.allGames': 'All games',
  'database.language': 'Language',
  'database.category': 'Category',
  'database.allCategories': 'All categories',
  'database.subcategory': 'Subcategory',
  'database.allSubcategories': 'All subcategories',
  'database.quickFilters': 'Quick filters',
  'database.allSentiment': 'All',
  'database.allLabels': 'All labels',
  'database.downloadCSV': 'Download CSV',
  'database.downloadJSON': 'Download JSONL',
  'database.noReviews': 'No reviews match these filters.',
  'database.reviewDetails': 'Review details',
  'database.categories': 'Categories',
  'database.metadata': 'Metadata',
  'database.export': 'Export',
  'database.sentiment': 'Recommendation',
  'database.type': 'Type',
  'database.previewExport': 'Preview export',
  'database.preparingExport': 'Preparing…',
  'database.applyFilters': 'Apply filters',
  // Settings
  'settings.title': 'Settings',
  'settings.subtitle': 'Account, storage, and diagnostics for this service.',
  'settings.appearance': 'Appearance',
  'settings.notifications': 'Notifications',
  'settings.account': 'Account',
  'settings.accountDesc': 'Manage your local instance settings.',
  'settings.diagnostics': 'Diagnostics',
  'settings.diagnosticsDesc': 'Use this when the backend is slow or unresponsive.',
  'settings.recheckBackend': 'Recheck backend',
  'settings.refreshLogs': 'Refresh logs',
  'settings.copyDiagnostics': 'Copy diagnostics',
  'settings.copied': 'Copied.',
  'settings.backendStatus': 'Backend status:',
  'settings.online': 'online',
  'settings.offline': 'offline',
  'settings.checking': 'checking',
  'settings.appVersion': 'App version',

  // Onboarding
  'onboarding.welcome': 'Welcome to STRA',
  'onboarding.welcomeDesc': 'Understand what players really think about any Steam game with AI-powered review analysis.',
  'onboarding.step1.title': 'Search & Analyze',
  'onboarding.step1.desc': 'Search for any Steam game and analyze up to 1,000 reviews with our AI classification system.',
  'onboarding.step2.title': 'Insights Dashboard',
  'onboarding.step2.desc': 'Get KPIs, recommendation trends, player segmentation, and category breakdowns at a glance.',
  'onboarding.step3.title': 'GenAI-Powered Features',
  'onboarding.step3.desc': 'Chat with an AI agent, generate summaries, and compare games side by side with configurable LLM providers.',
  'onboarding.step3.genaiPowered': 'GenAI Powered',
  'onboarding.step3.llmSetupPrompt': 'Set your provider, API key, and model in Settings to power classification, summaries, and chat.',
  'onboarding.step3.configureLlm': 'Set Up LLM',
  'onboarding.skip': 'Skip',
  'onboarding.back': 'Back',
  'onboarding.next': 'Next',
  'onboarding.getStarted': 'Get Started',
  'onboarding.feature.chat': 'Chat Agent',
  'onboarding.feature.chatDesc': 'Ask questions about player feedback',
  'onboarding.feature.summary': 'AI Summaries',
  'onboarding.feature.summaryDesc': 'Get instant insights from reviews',
  'onboarding.feature.compare': 'Compare Games',
  'onboarding.feature.compareDesc': 'Benchmark against competitors',

  // Onboarding - stat labels
  'onboarding.stat.reviewsAnalyzed': 'Reviews Analyzed',
  'onboarding.stat.aiCategories': 'AI Categories',
  'onboarding.stat.languages': 'Languages',

  // Onboarding - Step 2 section headers
  'onboarding.step2.keyMetrics': 'Key Metrics',
  'onboarding.step2.sentimentTrend': 'Recommendation Trend',
  'onboarding.step2.categoryBreakdown': 'Category Breakdown',

};

const zhTranslations: Record<string, string> = {
  'nav.home': '总览',
  'nav.dashboard': '数据看板',
  'nav.chat': '智能问答',
  'nav.chatMobile': '问答',
  'nav.compare': '游戏对比',
  'nav.database': '评论数据库',
  'nav.reports': '分析报告',
  'nav.settings': '系统设置',
  'common.loading': '加载中…',
  'common.error': '错误',
  'common.success': '成功',
  'common.cancel': '取消',
  'common.save': '保存',
  'common.delete': '删除',
  'common.edit': '编辑',
  'common.close': '关闭',
  'common.search': '搜索',
  'common.filter': '筛选',
  'common.sort': '排序',
  'common.reset': '重置',
  'common.apply': '应用',
  'common.calculate': '计算',
  'common.refresh': '刷新',
  'common.clearFilters': '清除筛选',
  'common.pending': '待处理',
  'common.reviews': '评论',
  'common.games': '游戏',
  'common.languages': '语言',
  'common.filters': '筛选条件',
  'common.all': '全部',
  'common.recommended': '推荐',
  'common.notRecommended': '不推荐',
  'common.issues': '问题',
  'common.requests': '需求',
  'common.evidence': '证据',
  'common.noData': '暂无数据',
  'dashboard.title': '数据总览',
  'dashboard.analyze': '开始分析',
  'dashboard.update': '更新最新评论',
  'dashboard.analyzing': '分析中…',
  'dashboard.noGames': '还没有分析过游戏',
  'dashboard.recommendation': '推荐率',
  'dashboard.issueRate': '问题率',
  'dashboard.requestRate': '需求率',
  'dashboard.welcome': '欢迎使用',
  'dashboard.welcomeTo': '欢迎使用 STRA',
  'dashboard.subtitle': '了解玩家真正关心什么，并将反馈转化为可执行的产品决策。',
  'dashboard.newAnalysis': '分析新游戏',
  'dashboard.newAnalysisDesc': '搜索 Steam 游戏，开始一次新的玩家声音分析。',
  'dashboard.searchPlaceholder': '搜索游戏，例如：博德之门 3',
  'dashboard.searching': '搜索中…',
  'dashboard.noGamesFound': '没有找到游戏，请尝试其他关键词。',
  'dashboard.recentAnalyses': '最近分析',
  'dashboard.recentDesc': '打开最近保存的分析结果。',
  'dashboard.viewAll': '查看全部',
  'dashboard.noAnalyses': '暂无分析记录',
  'dashboard.noAnalysesDesc': '搜索一个游戏，开始第一次分析。',
  'chat.title': '智能问答',
  'chat.subtitle': '基于玩家反馈的分析助手',
  'chat.placeholder': '输入你的问题…',
  'chat.send': '发送',
  'chat.newChat': '新建对话',
  'chat.history': '对话记录',
  'chat.context': '分析范围',
  'chat.noConversations': '暂无对话',
  'chat.export': '导出',
  'chat.newMobile': '新建',
  'chat.gamesSelected': '已选择 {count} 款游戏',
  'chat.gameSelected': '已选择 {count} 款游戏',
  'chat.selectGamesTitle': '选择要咨询的游戏',
  'chat.chooseGames': '最多选择 2 款游戏后即可开始问答',
  'chat.askAfterSelection': '已选择 {count} 款游戏，请在下方提问。',
  'chat.noAnalyzedGames': '暂无已分析的游戏',
  'chat.analyzeFirst': '请先完成一款游戏的分析。',
  'chat.goDashboard': '前往数据看板',
  'chat.selected': '已选择',
  'chat.pickQuestion': '推荐问题',
  'chat.pickQuestionHint': '点击问题开始，或在下方输入自己的问题。',
  'chat.chattingWith': '当前咨询：',
  'chat.noDate': '暂无日期',
  'chat.downloadPng': '下载 PNG',
  'chat.helpful': '回答有帮助',
  'chat.notHelpful': '回答没帮助',
  'chat.searchingReviews': '正在检索评论…',
  'chat.thinking': '正在思考…',
  'chat.inputHint': '按 Enter 检索评论并获取洞察',
  'chat.selectGameToStart': '请至少选择一款游戏后开始问答',
  'chat.errorProvider': '智能问答暂时无法连接 AI 服务，请在“系统设置”中检查 AI 服务提供商和 API Key 后重试。',
  'chat.errorRateLimit': '请求过于频繁，请稍后再试。',
  'chat.errorGeneric': '智能问答暂时无法处理这个问题，请稍后重试。',
  'compare.title': '游戏对比',
  'database.title': '评论数据库',
  'database.subtitle': '浏览已保存的全部玩家评论。',
  'database.stats': '数据库概览',
  'database.loadingStats': '加载统计中…',
  'database.noData': '暂无本地数据',
  'database.noDataDesc': '完成第一次分析后，评论数据会出现在这里。',
  'settings.title': '系统设置',
  'settings.subtitle': '配置 AI 模型、数据存储和系统诊断。',
  'settings.appearance': '外观',
  'settings.diagnostics': '系统诊断',
  'settings.diagnosticsDesc': '当服务变慢或无响应时，用于排查问题。',
  'settings.recheckBackend': '检查系统服务',
  'settings.refreshLogs': '刷新日志',
  'settings.copyDiagnostics': '复制诊断信息',
  'settings.backendStatus': '系统服务状态：',
  'settings.online': '正常',
  'settings.offline': '离线',
  'settings.checking': '检查中',
};

const jaTranslations: Record<string, string> = {
  'nav.home': '概要', 'nav.dashboard': 'ダッシュボード', 'nav.chat': 'AIチャット',
  'nav.chatMobile': 'チャット', 'nav.compare': 'ゲーム比較', 'nav.database': 'レビューDB',
  'nav.reports': '分析レポート', 'nav.settings': '設定',
  'common.loading': '読み込み中…', 'common.error': 'エラー', 'common.success': '成功',
  'common.cancel': 'キャンセル', 'common.save': '保存', 'common.delete': '削除',
  'common.close': '閉じる', 'common.search': '検索', 'common.filter': '絞り込み',
  'common.sort': '並べ替え', 'common.reset': 'リセット', 'common.apply': '適用',
  'common.refresh': '更新', 'common.clearFilters': '絞り込みを解除', 'common.pending': '保留中',
  'common.reviews': 'レビュー', 'common.games': 'ゲーム', 'common.languages': '言語',
  'common.all': 'すべて', 'common.recommended': 'おすすめ', 'common.notRecommended': 'おすすめしない',
  'common.issues': '課題', 'common.requests': '要望', 'common.evidence': '根拠', 'common.noData': 'データなし',
  'dashboard.title': 'データ概要', 'dashboard.analyze': '分析を開始', 'dashboard.analyzing': '分析中…',
  'dashboard.recommendation': 'おすすめ率', 'dashboard.issueRate': '課題率', 'dashboard.requestRate': '要望率',
  'dashboard.welcome': 'ようこそ', 'dashboard.welcomeTo': 'STRA へようこそ',
  'dashboard.subtitle': 'プレイヤーの声を理解し、実行可能なプロダクト判断につなげます。',
  'dashboard.newAnalysis': '新しいゲームを分析', 'dashboard.newAnalysisDesc': 'Steam のゲームを検索して分析します。',
  'dashboard.searchPlaceholder': 'ゲームを検索（例：Baldur’s Gate 3）', 'dashboard.searching': '検索中…',
  'dashboard.noGamesFound': 'ゲームが見つかりません。別のキーワードを試してください。',
  'dashboard.recentAnalyses': '最近の分析', 'dashboard.noAnalyses': '分析履歴はありません',
  'chat.title': 'AIチャット', 'chat.subtitle': 'プレイヤーフィードバック分析アシスタント',
  'chat.placeholder': '質問を入力…', 'chat.send': '送信', 'chat.newChat': '新しい会話', 'chat.history': '会話履歴',
  'compare.title': 'ゲーム比較', 'database.title': 'レビューDB', 'database.subtitle': '保存されたレビューを確認します。',
  'database.stats': 'データベース概要', 'database.loadingStats': '統計を読み込み中…',
  'database.noData': 'ローカルデータはありません', 'database.noDataDesc': '最初の分析を実行するとレビューが表示されます。',
  'settings.title': '設定', 'settings.subtitle': 'AIモデル、保存先、システム診断を設定します。',
  'settings.appearance': '外観', 'settings.diagnostics': 'システム診断',
  'settings.diagnosticsDesc': 'サービスが遅い、または応答しない場合に使用します。',
  'settings.recheckBackend': 'システムサービスを確認', 'settings.refreshLogs': 'ログを更新',
  'settings.copyDiagnostics': '診断情報をコピー', 'settings.backendStatus': 'システムサービス：',
  'settings.online': '正常', 'settings.offline': 'オフライン', 'settings.checking': '確認中',
};

export const LANGUAGE_OPTIONS: Array<{ value: Language; label: string }> = [
  { value: 'zh', label: '中文' },
  { value: 'en', label: 'English' },
  { value: 'ja', label: '日本語' },
];

function translatedValue(language: Language, key: string): string {
  if (language === 'zh') return zhTranslations[key] || translations[key] || key;
  if (language === 'ja') return jaTranslations[key] || translations[key] || key;
  return translations[key] || key;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'zh',
  setLanguage: () => {},
  t: (key) => translatedValue('zh', key),
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('zh');

  useEffect(() => {
    const stored = window.localStorage.getItem('stra-language');
    if (stored === 'zh' || stored === 'en' || stored === 'ja') setLanguageState(stored);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : language;
  }, [language]);

  function setLanguage(value: string) {
    const next: Language = value === 'en' || value === 'ja' ? value : 'zh';
    setLanguageState(next);
    window.localStorage.setItem('stra-language', next);
  }

  const contextValue: LanguageContextType = {
    language,
    setLanguage,
    t: (key) => translatedValue(language, key),
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
